### PR TITLE
Add docs to StringIO.

### PR DESCRIPTION
**Pull request by connorshea**

### CODE REVIEW

**Comment by connorshea** [comment]
Also, this is missing quite a few methods that Sorbet has. Maybe we should just import the RBI file? https://github.com/sorbet/sorbet/blob/master/rbi/stdlib/stringio.rbi

**Comment by soutaro** [comment]
@connorshea Yes. How about trying to import Sorbet RBI file and then writing types and tests?

**Comment by soutaro** [comment]
```
ruby-signature/lib/ruby/signature/errors.rb:19:in `check!': /__w/ruby-signature/ruby-signature/stdlib/builtin/string_io.rbs:67:59...67:79: ::Enumerator expects parameters [Elem, Return], but given args [::String] (Ruby::Signature::InvalidTypeApplicationError)
373
```

🔪

**Comment by connorshea** [comment]
@soutaro I think the `Enumerator[String]` should be changed to `Enumerator[String, self]` in this PR, right?

I also just opened an issue about fixing this in the rbi converter :) https://github.com/ruby/ruby-signature/issues/276

**Pull request merged**
