### PR TITLE
Add COPYING

### PR DESCRIPTION
**Pull request by soutaro**
Hello contributors!

We found that the repository does not contain any licensing declaration. (#147) So, I'd like to declare it is a 2-clause BSDL software.

1. I believe we can assume all of the contributors accept this change, because this repository is expected to be merged to ruby finally and 2-clause BSDL is the license of ruby.
2. I will merge this PR (to change the license) in two weeks, Jan 16, 2020.
   * Because of the assumption 1., I will do this unless someone says NO.
   * If you don't agree the license change, let me know until Jan 16.
3. If you have any questions, suggestion, concerns, or anything else, please let me know. Commenting on this PR is the best place for it.

I'm really sorry for the extra work and appreciate your contribution.

## Your options

* `+1` this PR if you agree the license change.
* Tell us if you don't agree the change.
* If you do nothing, you are supposed to agree this. (I believe this is reasonable because of 1. in the list above.)

## The deadline

Jan 16, 2020.

## Contributors

@hanachin @pocke @mame @mtsmfm @natsuokw @south37 @YutaGoto @ybiquitous @kunitoo @wat-aro @ohbarye @k0kubun @ykpythemind @szTheory @s4na @meganemura @kmizu @aikyo02 @MITSUBOSHI

### CODE REVIEW

**Comment by ybiquitous** [comment]
Thanks for your sharing!
I agree :+1:

**Comment by hsbt** [comment]
FYI: https://github.com/ruby/ruby is a 2-clause BSDL or Ruby license.

**Comment by soutaro** [comment]
@hsbt Thanks. I was misunderstanding.

The content of COPYING is not the conditions of 2-clause BSDL, but it defines the *Ruby license*. 💦

**Comment by soutaro** [comment]
Oh, it's over. Merging.

**Pull request merged**
