### PR TITLE
Add `rbs parse` subcommand

### PR DESCRIPTION
**Pull request by pocke**
This pull request will adds `rbs check` sub-command to check syntax error from .rbs files.

For example:

```bash
$ cat test.rbs
class C
  def foo: () ->
end

$ rbs check test.rbs
test.rbs:3:0: parse error on value: (kEND)
```

### CODE REVIEW

**Comment by soutaro** [comment]
The feature looks good. I'm wondering if there is a better name than `rbs check`. 

* `rbs parse`
* `rbs -C validate`
* `rbs syntax`
* ... any other?

I don't think one of the above is better...

**Comment by pocke** [comment]
Hmm, I understand your concern. 
I have the following ideas, but I'm not sure they are better.

* `rbs syntax-check`
* `rbs syntax_check`
* `rbs validate`

**Comment by soutaro** [comment]
I'd like to propose `rbs parse`. It parses the input and prints syntax errors if detected.

**Comment by pocke** [comment]
Sure! I renamed the command to `rbs parse`. 38e36922d93808c80c416f5879d1795a7a356a2b

**Comment by soutaro** [comment]
@pocke Thanks! 🎉

**Pull request merged**
