### PR TITLE
Add String#encode and #encode!

### PR DESCRIPTION
**Pull request by mtsmfm**

### CODE REVIEW

**Comment by soutaro** [comment]
I found that we cannot write literal type for symbols ending with `?`. 😮

**Comment by mtsmfm** [comment]
> I found that we cannot write literal type for symbols ending with `?`. 😮

True...

**Comment by mtsmfm** [comment]
I fixed conflict

**Comment by mtsmfm** [comment]
@soutaro Can you review?

**Comment by soutaro** [comment]
#83 would have broken this? @mtsmfm

**Comment by mtsmfm** [comment]
> #83 would have broken this? @mtsmfm

Ah, yes!
I've fixed

**Pull request merged**
